
version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgresql14-playground-1
    restart: always
    env_file: .pg_env
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

  pgadmin:
    image: dpage/pgadmin4
    env_file: .pg_env
    ports:
      ##
      # http://localhost:8081
      #
      - "8081:80"

volumes:
  dbdata:
