= Help

== Running the tests

Get the first test compiling, linking and passing by following the https://blog.cleancoder.com/uncle-bob/2014/12/17/TheCyclesOfTDD.html[three rules of test-driven development].

The included makefile can be used to create and run the tests using the `test` task.

[,console]
----
$ make test
----

Create just the functions you need to satisfy any compiler errors and get the test to fail.
Then write just enough code to get the test to pass.
Once you've done that, move onto the next test.

As you progress through the tests, take the time to refactor your implementation for readability and expressiveness and then go on to the next test.

Try to use standard C99 facilities in preference to writing your own low-level algorithms or facilities by hand.

== Checking for memory leaks

The makefile comes also with a build that checks some common mistakes regarding memory leaks and out of bound access to arrays.
To run these checks, use the following at the command line:

[,console]
----
$ make memcheck
----

== Submitting your solution

You can submit your solution using the `exercism submit reverse_string.c reverse_string.h` command.
This command will upload your solution to the Exercism website and print the solution page's URL.

It's possible to submit an incomplete solution which allows you to:

* See how others have completed the exercise
* Request help from a mentor

== Need to get help?

If you'd like help solving the exercise, check the following pages:

* The https://exercism.org/docs/tracks/c[C track's documentation]
* The https://forum.exercism.org/c/programming/c[C track's programming category on the forum]
* https://forum.exercism.org/c/programming/5[Exercism's programming category on the forum]
* The https://exercism.org/docs/using/faqs[Frequently Asked Questions]

Should those resources not suffice, you could submit your (incomplete) solution to request mentoring.

Make sure you have read the https://exercism.org/docs/tracks/c[C track-specific documentation] on the Exercism site.
This covers the basic information on setting up the development environment expected by the exercises.

== Submitting Incomplete Solutions

If you are struggling with a particular exercise, it is possible to submit an incomplete solution so you can see how others have completed the exercise.

== Resources

To get help if having trouble, you can use the following resources:

* http://stackoverflow.com/questions/tagged/c[StackOverflow] can be used to search for your problem and see if it has been answered already.
You can also ask and answer questions.
* https://en.cppreference.com/w/c[CPPReference] can be used to look up information on C concepts, operators, types, standard library functions and more.
* https://www.tutorialspoint.com/cprogramming/[TutorialsPoint] has similar content as CPPReference in its C programming section.
* https://www.amazon.com/Programming-Language-2nd-Brian-Kernighan/dp/0131103628/[The C Programming] book by K&R is the original source of the language and is still useful today.
