= Date and Time
:icons: font
:toc: left

== Intro

link:https://discord.com/channels/518658712081268738/650031651845308419/1077198754270171176[I asked on Ruby Discord about how to properly learn/practice date and time stuff^].

In short, we should use the `Time` class about 90% of the time (no pun intended).

`DateTime` is deprecated (https://ruby-doc.com/stdlib-3.1.0/libdoc/date/rdoc/DateTime.html[DateTime docs]).
`Date` and `Time` are not deprecated.

[quote, DateTime class, DateTime]
____
So when should you use `DateTime` in Ruby and when should you use Time?

Almost certainly you'll want to use `Time` since your app is probably dealing with current dates and times.
However, if you need to deal with dates and times in a historical context you'll want to use `DateTime` to avoid making the same mistakes as UNESCO.

If you also have to deal with timezones then best of luck - just bear in mind that you'll probably be dealing with local solar times, since it wasn't until the 19th century that the introduction of the railways necessitated the need for Standard Time and eventually timezones.
____

== Simple Examples

Creating a date for the first day of any given month is easy:

[source,ruby]
----
Date.new(2023, 7, 1)
#         /    |   \
#        /     |    \
#       v      v     v
#     year   month   day
----

A date for the *last* day of a given month is harder.
Some months have 30 days, others 31.
February has 28 days, except on leap years when it has 29 days.

Thankfully, we can use negative values:

[source,irb]
----
>> Date.new(2023, 2, -1)
=> #<Date: 2023-02-28 ((2460004j,0s,0n),+0s,2299161j)>

>> Date.new(2024, 2, -1)
=> #<Date: 2024-02-29 ((2460370j,0s,0n),+0s,2299161j)>
----

Note that in 2024 is a leap year, and therefore February in 2024 has 29 days.
The negative day index allows one to easy compute the last day of any given month.

== Days of first week of any month

.cal -y 2023
----
                               2023

       January               February                 March
Su Mo Tu We Th Fr Sa   Su Mo Tu We Th Fr Sa   Su Mo Tu We Th Fr Sa
 1  2  3  4  5  6  7             1  2  3  4             1  2  3  4
 8  9 10 11 12 13 14    5  6  7  8  9 10 11    5  6  7  8  9 10 11
15 16 17 18 19 20 21   12 13 14 15 16 17 18   12 13 14 15 16 17 18
22 23 24 25 26 27 28   19 20 21 22 23 24 25   19 20 21 22 23 24 25
29 30 31               26 27 28               26 27 28 29 30 31

        April                   May                   June
Su Mo Tu We Th Fr Sa   Su Mo Tu We Th Fr Sa   Su Mo Tu We Th Fr Sa
                   1       1  2  3  4  5  6                1  2  3
 2  3  4  5  6  7  8    7  8  9 10 11 12 13    4  5  6  7  8  9 10
 9 10 11 12 13 14 15   14 15 16 17 18 19 20   11 12 13 14 15 16 17
16 17 18 19 20 21 22   21 22 23 24 25 26 27   18 19 20 21 22 23 24
23 24 25 26 27 28 29   28 29 30 31            25 26 27 28 29 30
30

        July                  August                September
Su Mo Tu We Th Fr Sa   Su Mo Tu We Th Fr Sa   Su Mo Tu We Th Fr Sa
                   1          1  2  3  4  5                   1  2
 2  3  4  5  6  7  8    6  7  8  9 10 11 12    3  4  5  6  7  8  9
 9 10 11 12 13 14 15   13 14 15 16 17 18 19   10 11 12 13 14 15 16
16 17 18 19 20 21 22   20 21 22 23 24 25 26   17 18 19 20 21 22 23
23 24 25 26 27 28 29   27 28 29 30 31         24 25 26 27 28 29 30
30 31

       October               November               December
Su Mo Tu We Th Fr Sa   Su Mo Tu We Th Fr Sa   Su Mo Tu We Th Fr Sa
 1  2  3  4  5  6  7             1  2  3  4                   1  2
 8  9 10 11 12 13 14    5  6  7  8  9 10 11    3  4  5  6  7  8  9
15 16 17 18 19 20 21   12 13 14 15 16 17 18   10 11 12 13 14 15 16
22 23 24 25 26 27 28   19 20 21 22 23 24 25   17 18 19 20 21 22 23
29 30 31               26 27 28 29 30         24 25 26 27 28 29 30
                                              31
----

The idea is that we start with day 1 of a month, and then iterate up to 7 times, checking if the `wday` is 6, which means we are at Saturday, the last day of the week.

Example with January.
The first week has the full seven days.

[source,ruby]
----
dates = []
date = Date.new(2023, 1, 1)

7.times do
  dates << date
  break if date.wday == 6
  date = date.next_day
end

dates.each do |d|
  p Date::DAYNAMES[d.wday]
end
#=> "Sunday"
#=> "Monday"
#=> "Tuesday"
#=> "Wednesday"
#=> "Thursday"
#=> "Friday"
#=> "Saturday"
----


Example with February.
First week goes from Wed to Sat.

[source,ruby]
----
dates = []
date = Date.new(2023, 2, 1)

7.times do
  dates << date
  break if date.wday == 6
  date = date.next_day
end

dates.each do |d|
  p Date::DAYNAMES[d.wday]
end
#=> "Wednesday"
#=> "Thursday"
#=> "Friday"
#=> "Saturday"
----

This is the month July of 2023:

.cal 7 2023
----
      July 2023
Su Mo Tu We Th Fr Sa
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31
----

[source,ruby]
----
dates = []
date = Date.new(2023, 7, 1)
7.times do
  dates << date
  break if date.wday == 6
  date = date.next_day
end

dates.each do |d|
  p Date::DAYNAMES[d.wday]
end
#=> "Saturday"
----

== Number of days in a month

The link:https://ruby-doc.com/stdlib-2.5.2/libdoc/date/rdoc/Date.html#method-i-3C-3C[Date class^] provides the `#<<` method:

[quote, attribution, cite title]
____
quote
____


[quote, Ruby Docs, Date class #<< method]
____
Returns a date object pointing `n` months before `self`. When the same day doesn't exist for the corresponding month, the last day is used instead.
____

For example, 2024 is a leap year.
If we have a date of March 31, 2024, the previous month is February, which on a leap year has 29 days (not 28).

Because February cannot possibly contain the day 31 (or 30), as the docs mention, it will use the last day of the month, which in this case is 29.

[source,irb]
----
>> d = Date.new(2024, 3, 31)
=> #<Date: 2024-03-31 ((2460401j,0s,0n),+0s,2299161j)>

>> feb29 = d << 1
=> #<Date: 2024-02-29 ((2460370j,0s,0n),+0s,2299161j)>
----

And we can therefore use this code snippet to get the number of days of any month:

.get number of days in given month
[source,ruby]
----
##
# Returns the number of days in a given month.
#
# @param year [Integer]
# @param month [Integer] A month number between 1 and 12 (inclusive).
# @return [Integer]
#
def num_days_in_month(year, month)
  dec31 = Date.new(year, 12, 31)
  (dec31 << (12 - month)).day
end
----

Most days will have a corresponding day in any given month, but a few will not.
For example, a month may have 31 days, while a month before that may have only 30 days, in this (and similar cases), there is no corresponding day 31.
The same can happen to day 30 and 29.

Another approach is this:

[source,irb]
----
>> (Date.new(2024, 2).next_month - 1).day
=> 29
----

In this case, we want to know the number of days in February of 2024 (a leap year), which should contain 29 days.

`Date.new(year, month)` without the day parameter causes the date to be constructed with day 1.
Then `next_month` goes to the next month, on the same day, which means we are now in March 1st, 2024.
Then we subtract 1, which means “subtract one day” from the date, effectively making it the last day of the previous month.
The resulting date is 2024-02-29.
The `day` method returns the current day, which is 29.
Since 29 is the last day of 2024-02, 29 is the number of days for that month.
