= instanceof :: TypeScript
:page-tags: typescript runtime instanceof
:toc: left
:icons: font

== Intro

Unlike `typeof` which can be used both in _value level_ and _type level_, `instanceof` can only be used at _value level_.

.node repl
----
> 'xywz' instanceof String
false
> String('zywz') instanceof String
false
> new String('zywz') instanceof String
true
----

Both `'xywz'` and `String('xywz')` create string literals, and those are not instances of the `String` constructor.

== Classes

In TypeScript, a class contributes to both the value/expression space, _and_ the type space.

That means `instanceof` can be used in this case:

[source,typescript]
----
class Jedi {}
const yoda = new Jedi();
log(yoda instanceof Jedi);
//=> true
----

Here, `Jedi` is a class, which exist but as a runtime type and value.

== Types and Interfaces

But this is one case where we cannot use `instanceof`:

[source,typescript]
----
interface Animal {
  walk(): void;
};

interface Bird extends Animal {
  fly(): void;
};

const a = new Bird();

a instanceof Bird ? fly() : walk()
//            ~
//             \
//              \
//               v
// ~ 'Bird' only refers to a type, but is being
// ~ used as a value here.
----

`Bird` is a TS interface, a type-level only entity.
It gets erased during transpilation and does not exist at runtime, and `instanceof` (unlike `typeof`) is a runtime only check.

So remember, a class contributes both to type level and value/expression level (so it can be used at runtime), but a type created with `type` or `interface` keywords do not really exist at runtime.
