= Run Commands on Selected Files :: Git
:page-tags: git command-line shell filter select command
:toc: left

== Open files touched by last commit in vim

[tags="git log"]
[source,shell-session]
----
$ git log -1 --name-only --pretty=format:
src/main.c
src/utils.c
src/utils.h
----

The output is each file on its own line.
That can be passed to vim:

[source,shell-session]
----
$ vim $(git log -1 --name-only --pretty=format:)
13 files to edit
----

Just before vim actually opens the file, it displays a message of how many files it (vim) is going to edit.
After you close the editor, the message is still on the terminal.

And it works for more than one commit too:

[source,shell-session]
----
$ vim $(git log -15 --name-only --pretty=format: HEAD~1)
81 files to edit
----

In any case, we used `--name-only` in conjunction with `--pretty=format:` with no format specifier after the colon (`:`) precisely because we want to output the filenames and nothing else.

The output may contain some empty lines, but those will simply be ignored by git, so we don't need to clean them up manually, but we can anyway, just for kicks.
Let's see this example from vim repository itself:

[source,shell-session]
----
~/work/src/projects/others/vim [master|u=]
$ git log -5 --name-only --pretty='format:'
runtime/autoload/gzip.vim
runtime/ftplugin/perl.vim
runtime/ftplugin/ruby.vim

src/ex_docmd.c
src/list.c
src/macros.h
src/testdir/test_crash.vim
src/testdir/test_usercommands.vim
src/userfunc.c
src/version.c

src/testdir/test_vim9_disassemble.vim
src/version.c

src/testdir/test_recover.vim
src/version.c
----

Then we can use sed (or tr) to exclude the empty lines from the output:

[source,shell-session]
----
$ git log -5 --name-only --pretty='format:' | sed '/^$/d'
runtime/autoload/gzip.vim
runtime/ftplugin/perl.vim
runtime/ftplugin/ruby.vim
Filelist
src/ex_docmd.c
src/list.c
src/macros.h
src/testdir/test_crash.vim
src/testdir/test_usercommands.vim
src/userfunc.c
src/version.c
src/testdir/test_vim9_disassemble.vim
src/version.c
src/testdir/test_recover.vim
src/version.c
----

And pass the result to vim, just like earlier:

[source,shell-session]
----
$ vim $(git log -5 --name-only --pretty='format:' | sed '/^$/d')
17 files to edit
----

=== Credits and references

Got the gist of the idea form link:https://logc.github.io/blog/2015/07/15/open-files-from-last-commit-in-vim/[this blog post by Luis Osa^] and just added more details to the explanation.
