# Encoding and UTF-8
:icons: font
:toc: left
:experimental:

== Page Break

0x0c is the _page break_ character.

Those page break markers display something like "^L" in both vim and emacs.

=== Emacs

In emacs, we can insert them with kbd:[C-q C-l] and navigate between them with kbd:[C-x [] and kbd:[C-x ].

From emacs, kbd:[C-h i m Emacs RET] kbd:[m Pages RET].

* link:https://www.gnu.org/software/emacs/manual/html_node/emacs/Pages.html[Pages :: Emacs Manual].o


=== Vim

In vim, the digraph is `FF`, or with which means we can insert them with kbd:[CTRL-K FF]
Or, insert the char with kbd:[CTRL-V CTRL-L]
Then one can search for those page breaks with something like kbd:[/CTRL-V CTRL-L] or kbd:[?CTRL-V CTRL-L] followed by kbd:[n] or kbd:[N] to search forwards and backwards.

[TIP]
====
If kbd:[CTRL-V] is mapped to some other thing (e.g. paste text), kbd:[CTRL-Q] can also be used.
====

One example where I used this is for my The Little Schemer solutions, where code for each chapter is preceeded by a page break character so I can easily navigate between “pages”.

See:

.in vim help
----
:help insert.txt
:help i_CTRL-V
:help i_CTRL-Q
----

If we don't want kbd:[C-s] to lock and terminal (which is unlocked with kbd:[C-q]):

.bashrc
----
stty -ixon
----

* link:https://www.emacswiki.org/emacs/PageBreaks[Page Breaks :: EmacsWiki]
