= HackerRank SQL Challenges
:toc: left
:icons: font
:source-highlighter: highlight.js


== Revising The Select Query I

* https://www.hackerrank.com/challenges/revising-the-select-query[Revising the Select Query I :: HackerRank SQL Challenge].

[source,sql]
----
SELECT
    id
  , name
  , countrycode
  , district
  , population
FROM city
WHERE population >= 100000
AND countrycode = 'USA';
----

We can replace all column names with the start `*`, but this is more readable as all column names are explicitly stated in the query.

Also, we could use `LIKE` in place of `=` for this case: `... AND countrycode LIKE 'USA'`.

== Revising the Select Query II

* https://www.hackerrank.com/challenges/revising-the-select-query-2[Revising the Select Query II :: HackerRank SQL Challenge].

[source,sql]
----
SELECT name
FROM city
WHERE population > 120000
AND countrycode LIKE 'USA';
----

== Select All

* https://www.hackerrank.com/challenges/select-all-sql[Select All :: HackerRank SQL Challenge].

[source,sql]
----
SELECT
    id
  , name
  , countrycode
  , district
  , population
FROM city;
----

Again, writing the column names explicitly makes it more self-documenting than simply using `*`.

== Select By ID

* https://www.hackerrank.com/challenges/select-by-id[Select By ID :: HackerRank SQL Challenge].

[source,sql]
----
SELECT
    id
  , name
  , countrycode
  , district
  , population
FROM city
WHERE id = 1661;
----

== Japanese Cities' Attributes

* https://www.hackerrank.com/challenges/japanese-cities-attributes[Japanese Cities' Attributes :: HackerRank SQL Challenge].

[source,sql]
----
SELECT name
FROM city
WHERE countrycode = 'JPN';
----

== Weather Observation Station 1

* https://www.hackerrank.com/challenges/weather-observation-station-1[Weather Observation Station 1 :: HackerRank SQL Challenge].

[source,sql]
----
SELECT
    city
  , state
FROM station;
----

== Weather Observation Station 2

* https://www.hackerrank.com/challenges/weather-observation-station-2[Weather Observation Station 2 :: HackerRank SQL Challenge].

[source,sql]
----
SELECT
    ROUND(SUM(lat_n), 2) AS lat
  , ROUND(SUM(long_w), 2) AS lon
FROM station;
----

We can `SUM` any numeric column, e.g.:

[source,sql]
----
SELECT SUM(id) FROM users;
----

And also `ROUND(value, num_decimal_places)`, e.g.:

.psql session
[source,text]
----
mydb=# SELECT ROUND(3.141592653589793, 5);
  round
---------
 3.14159
----

So we basically round the result of the sum and rename the output columns as `lat` and `lon`.
