= Simply SQL Book Questions
:page-subtitle: Databases and SQL
:page-tags: database sql exercise book
:toc: left
:icons: font
:source-highlighter: highlight.js

== Intro

Some practice questions based on the book Simply SQL.

== The WHERE Clause (chapter 4)

=== Q1

Application: Teams and Games.

[role="qanda"]
====

Select the the fields `id` and `name` of the team with id equal to 9.

.Show me!
[%collapsible]
=====

[source,sql]
----
SELECT
  id
, name
FROM
  teams
WHERE
  id = 9;
----

.Result
[source,text]
----
 id |   name
----+-----------
  9 | Riff Raff
(1 row)
----
=====
====

=== Q2

Application: Teams and Games.

[role="qanda"]
====

Select the `id` and `name` fields of the team with IDs not equal to 9.

.Show me!
[%collapsible]
=====

[source,sql]
----
SELECT
  id
, name
FROM
  teams
WHERE
  id <> 9;
----

.Result
[source,text]
----
 id |  name
----+---------
 37 | Havoc
 63 | Brewers
(2 rows)
----
=====
====

=== Q3

Application: Shopping Cart.

[role="qanda"]
====
Select items with price not equal to 9.37.

.Show me!
[%collapsible]
=====
Equal to 9.37:

[source,sql]
----
SELECT
  id
, name
, type
, price
FROM
  items
WHERE
  price <> 9.37;
----

.Result
[source,text]
----
  id  |      name       |  type   | price
------+-----------------+---------+-------
 5022 | gadget          | doodads | 19.37
 5023 | dingus          | gizmos  | 29.37
 5041 | gewgaw          | widgets |  5.00
 5042 | knickknack      | doodads | 10.00
 5043 | whatnot         | gizmos  | 15.00
 5061 | bric-a-brac     | widgets |  2.00
 5062 | folderol        | doodads |  4.00
 5063 | jigger          | gizmos  |  6.00
 5901 | doohickey       | widgets | 12.00
 5931 | contraption     | widgets | 49.95
 5932 | whatchamacallit | doodads | 59.95
 5911 | thingamajig     | widgets | 22.22
 5912 | thingamabob     | doodads | 22.22
 5913 | thingum         | gizmos  | 22.22
 5937 | whatsis         | gizmos  | 93.70
(15 rows)
----
=====
====

=== Q4

Application: Shopping Cart.

[role="qanda"]
====
Select the fields `name` and `type` for items whose name include the string “thing”.

.Show me!
[%collapsible]
=====
[source,sql]
----
SELECT
  name
, type
FROM
  items
WHERE
  name LIKE 'thing%';
----

.Result
[source,text]
----
    name     |  type
-------------+---------
 thingie     | widgets
 thingamajig | widgets
 thingamabob | doodads
 thingum     | gizmos
(4 rows)
----
=====
====

=== Q5

Application: Shopping Cart.

[role="qanda"]
====
Select the fields `name` and `type` for items whose name does not include the string “thing”.

[source,sql]
----
SELECT
  name
, type
FROM
  items
WHERE
  name NOT LIKE 'thing%';
----

.Show me!
[%collapsible]
=====

.Result
[source,text]
----
      name       |  type
-----------------+---------
 gadget          | doodads
 dingus          | gizmos
 gewgaw          | widgets
 knickknack      | doodads
 whatnot         | gizmos
 bric-a-brac     | widgets
 folderol        | doodads
 jigger          | gizmos
 doohickey       | widgets
 gimmick         | doodads
 dingbat         | gizmos
 contraption     | widgets
 whatchamacallit | doodads
 whatsis         | gizmos
(14 rows)
----
=====
====

=== Q6

Application: Shopping Cart.

[role="qanda"]
====
Select the fields `name` and `price` for items with price ranging from 5.00 to 10.00, inclusive.
Do it using the `BETWEEN` operator and then using comparison operators.

.Show me!
[%collapsible]
=====
Using between:

[source,sql]
----
SELECT
  name
, price
FROM
  items
WHERE
  price BETWEEN 4.00 AND 10.00;
----

.Result
[source,text]
----
    name    | price
------------+-------
 folderol   |  4.00
 gewgaw     |  5.00
 jigger     |  6.00
 thingie    |  9.37
 gimmick    |  9.37
 dingbat    |  9.37
 knickknack | 10.00
 (7 rows)
----
Using comparison operators:

[source,sql]
----
SELECT
  name
, price
FROM
  items
WHERE
  4.00 <= price AND price <= 10.00
ORDER BY price ASC;
----

.Result
[source,text]
----
    name    | price
------------+-------
    name    | price
------------+-------
 folderol   |  4.00
 gewgaw     |  5.00
 jigger     |  6.00
 thingie    |  9.37
 gimmick    |  9.37
 dingbat    |  9.37
 knickknack | 10.00
(7 rows)
----

[NOTE]
======
The comparison could be like this too:

[source]
----
price >= 4.00 AND price <= 10.00
----
======
=====
====

=== Q7

Application: Shopping Cart.

[role="qanda"]
====
Select the fields `id`, `name` and `billaddr` for customers whose name is either “A. Jones” or “B. Smith”.

.Show me!
[%collapsible]
=====
[source,sql]
----
SELECT
  id
, name
, billaddr
FROM
  customers
WHERE
     name = 'A. Jones'
  OR name = 'B. Smith';
----

.Result
[source,text]
----
 id  |   name   |          billaddr
-----+----------+----------------------------
 710 | A. Jones | 123 Sesame St., Eureka, KS
 730 | B. Smith | 456 Sesame St., Eureka, KS
----
=====
====

=== Q8a

Application: Shopping Cart.

[role="qanda"]
====
Select the user name, cart id, and items id on that cart where the user is either “A. Smith” or “B. Jones” and the name of the items they bought is “thingum”.

You'll need to join four tables for this.
Careful with the precedence of `AND` over `OR`.

.Show me!
[%collapsible]
=====
[source,sql]
----
SELECT
  customers.name AS customer
, carts.id       AS cart
, items.name     AS item
FROM
  customers
INNER JOIN carts
  ON carts.customer_id = customers.id
INNER JOIN cartitems
  ON cartitems.cart_id = carts.id
INNER JOIN items
  ON items.id = cartitems.item_id
WHERE
  (
       customers.name = 'A. Jones'
    OR customers.name = 'B. Smith'
  )
    AND items.name = 'thingum';
----

.Result
[source,text]
----
 customer | cart |  item
----------+------+---------
 A. Jones | 2131 | thingum
(1 row)
----

[NOTE]
======
Observe the use of parenthesis around the `OR` condition to give it precedence over `AND`.
======
=====
====

=== Q8b

Application: Shopping Cart.

[role="qanda"]
====
Repeat the same query as the previous question but now using `IN` the place of the `OR` condition.

.Show me!
[%collapsible]
=====
[source,sql]
----
SELECT
  customers.name  AS customer
, carts.id        AS cart
, items.name      AS item
FROM
  customers
INNER JOIN carts
  ON carts.customer_id = carts.id
INNER JOIN cartitems
  ON cartitems.cart_id = carts.id
INNER JOIN items
  ON items.id = cartitems.item_id
WHERE
  customers.name IN ('A. Jones', 'B. Smith')
    AND items.name = 'thingum';
----

.Result
[source,text]
----
 customer | cart |  item
----------+------+---------
 A. Jones | 2131 | thingum
(1 row)
----
=====
====

=== Question TMP

Application: Shopping Cart.

[role="qanda"]
====
Using `EXISTS` and a correlated subquery, display all customer names that have a cart.

.Show me!
[%collapsible]
=====

[source,sql]
----
SELECT
  customers.name
FROM
  customers
WHERE
  EXISTS (
    SELECT
      1
    FROM
      carts
    WHERE
      carts.customer_id = customers.id
  );
----
=====
====
