= Help

== Running the tests

Simply type `make chez` if you're using ChezScheme or `make guile` if you're using GNU Guile.

== Using the REPL

* Enter `test.scm` at the repl prompt.
* Develop your solution in the file `problem.scm` reloading as you go.
* Run `(test)` to check your solution.

== Submitting your solution

You can submit your solution using the `exercism submit hello-world.scm` command.
This command will upload your solution to the Exercism website and print the solution page's URL.

It's possible to submit an incomplete solution which allows you to:

* See how others have completed the exercise
* Request help from a mentor

== Need to get help?

If you'd like help solving the exercise, check the following pages:

* The https://exercism.org/docs/tracks/scheme[Scheme track's documentation]
* The https://forum.exercism.org/c/programming/scheme[Scheme track's programming category on the forum]
* https://forum.exercism.org/c/programming/5[Exercism's programming category on the forum]
* The https://exercism.org/docs/using/faqs[Frequently Asked Questions]

Should those resources not suffice, you could submit your (incomplete) solution to request mentoring.

To get help if you're having trouble, you can use one of the following resources:

* https://www.reddit.com/r/scheme[/r/scheme] is the Scheme subreddit.
* http://stackoverflow.com/questions/tagged/scheme[StackOverflow] can be used to search for your problem and see if it has been answered already.
You can also ask and answer questions.
