= ch02 SELECT Statement

== SELECT

The `SELECT` and `FROM` clauses are mandatory.
It can include optional clauses to filter, group and sort the results.

----
SELECT expression(s) involving keywords, identifiers, and constants
FROM tabular structure(s)
[WHERE clause]
[GROUP BY clause]
[HAVING clause]
[ORDER BY clause]
----

Like in unix-like man pages, things inside square brackets mean they are optional.

----
CREATE DATABASE simplysql_cms_devel WITH
    ENCODING='UTF-8'
    OWNER=devel
    LC_CTYPE='en_US.UTF-8'
    LC_COLLATE='en_US.UTF-8'
    TEMPLATE=template0
    CONNECTION LIMIT=3;
----

[,console]
----
$ docker inspect postgresql14-playground-1 | grep IPAddress
"IPAddress": "172.19.0.3",

$ psql -h 172.19.0.3 -U -d simplysql_cms_devel -W

$ pg_dump -h 172.19.0.3 -U devel simplysql_cms_devel
(dumps everything to STDOUT)

$ mkdir -pv ./src/databases-sql/dumps
mkdir: created directory './src/databases-sql/dumps'

$ pg_dump \
    -h 172.19.0.3 \
    -U devel \
    simplysql_cms_devel \
    -f ./src/databases-sql/dumps/db_simplysql_cms_bkp_01.sql
Password:
(no output, but database dumped to file)

$ du -h !$
du -h ./src/databases-sql/dumps/db_simplysql_cms_bkp_01.sql
4.0K	./src/databases-sql/dumps/db_simplysql_cms_bkp_01.sql
----

== FROM

----
SELECT
    title
  , category
FROM entries;

title            | category
-----------------------------+----------
 What If I Get Sick and Die? | angst
 Uncle Karl and the Gasoline | humor
 Be Nice to Everybody        | advice
 Hello Statue                | humor
 The Size of Our Galaxy      | science
(5 rows)
----

The query _selected_ two columns _from_ a table producing a tabular result.

== WHERE

`WHERE` is optional and when used acts as a _filter_.
It specifies a **************condition**************.
In this case, filter entries whose ID is exactly 524.

----
SQL> \x
Expanded display is on.
SQL> SELECT
        title
  , created
  , content
FROM entries
WHERE id = 524;
-[ RECORD 1 ]--------------------------------------------------------------------
title   | Uncle Karl and the Gasoline
created | 2009-02-28 00:00:00
content | When I was about nine or ten, my Uncle Karl, who
          (rest of large text ...)
----

A column can be part of a filter clause and not present in the `SELECT` clause.
Here, `id` was used in the `WHERE` clause but not in the `SELECT` clause.

== GROUP BY

`GROUP BY` is ***************aggregation***************.
It produces a single row per group.

----
SQL> SELECT category FROM entries;
 category
----------
 angst
 advice
 humor
 science
 humor
(5 rows)
----

We have four categories (not five).

----
SQL> SELECT
    category
  , COUNT(*) AS articles
FROM entries
GROUP BY category;

 category | articles
----------+----------
 science  |        1
 angst    |        1
 advice   |        1
 humor    |        2
(4 rows)
----

Note that the count of entries are grouped by category.

`COUNT()` is an aggregate function.

== HAVING

`HAVING` works in conjunction with `GROUP BY`.

----
SQL> SELECT
    category
  , COUNT(*) AS articles
FROM entries
GROUP BY category
HAVING COUNT(*) > 1;

 category | articles
----------+----------
 humor    |        2
(1 row)
----

The `HAVING` clause operates only on group rows, and acts as a filter on them in exactly the same way that the `WHERE` clause acts as a filter on table rows.

=== GROUP BY vs HAVING

* `WHERE`: filters table rows.
* `HAVING`: filters `GROUP BY` group rows.

== ORDER BY

`ORDER BY` _sorts_ the rows.

----
SQL> SELECT
    title
 , created
FROM entries
ORDER BY created DESC;

            title            |       created
-----------------------------+---------------------
 The Size of Our Galaxy      | 2009-04-03 00:00:00
 Hello Statue                | 2009-03-17 00:00:00
 Be Nice to Everybody        | 2009-03-02 00:00:00
 Uncle Karl and the Gasoline | 2009-02-28 00:00:00
 What If I Get Sick and Die? | 2008-12-30 00:00:00
(5 rows)
----

Oder based on the created date, _descending_.
There is also `ASC`, which is the default behavior anyways.

Multiple columns can be used with `ORDER BY`, which means the `ORDER BY` clause allows any number of major and minor keys.

----
SQL> SELECT
    title
 , category
 , created
FROM entries
ORDER BY
    category ASC
  , created DESC;

            title            | category |       created
-----------------------------+----------+---------------------
 Be Nice to Everybody        | advice   | 2009-03-02 00:00:00
 What If I Get Sick and Die? | angst    | 2008-12-30 00:00:00
 Hello Statue                | humor    | 2009-03-17 00:00:00
 Uncle Karl and the Gasoline | humor    | 2009-02-28 00:00:00
 The Size of Our Galaxy      | science  | 2009-04-03 00:00:00
(5 rows)
----

NOTE: A column being used in the `ORDER BY` clause does not need to be in the `SELECT` clause.
Or example, we can order by `category`, but `category` is not required to be in the `SELECT` clause.
