= ch05 GROUP BY
:page-subtitle: Simply SQL (book notes) | Databases and SQL
:page-tags: database sql book note
:toc: left
:icons: font

`GROUP BY` has an effect on the results of the `FROM` clause and filtered by the `WHERE` clause.

The Latin expression "`E pluribus unum`" on USA coins represents "`melting pot`".
It literally means "`out of many, one.`" This is more or less what `GROUP BY` does.
It groups together data from `FROM` and `WHERE` clauses and produces a ******single****** row in a result set _for each distinct group_.

== Grouping is more than sequencing.

Grouping is more than simply sequencing data.
Sequencing simply means sorting the data into a certain order.
Grouping does involve an aspect of sequencing, but it goes beyond that.

*Detail queries* return *detail rows*, ungrouped results -- columns and rows as they are stored in the database.

We'll learn about *group rows* in this chapter.

NOTE: Started this chapter but should have started chapter 04 about the WHERE clause.
