= Armstrong Numbers
:toc: left

Welcome to Armstrong Numbers on Exercism's C Track.
If you need help running the tests or submitting your code, check out `HELP.md`.

== Instructions

An https://en.wikipedia.org/wiki/Narcissistic_number[Armstrong number] is a number that is the sum of its own digits each raised to the power of the number of digits.

For example:

* 9 is an Armstrong number, because `+9 = 9^1 = 9+`
* 10 is _not_ an Armstrong number, because `+10 != 1^2 + 0^2 = 1+`
* 153 is an Armstrong number, because: `+153 = 1^3 + 5^3 + 3^3 = 1 + 125 + 27 = 153+`
* 154 is _not_ an Armstrong number, because: `+154 != 1^3 + 5^3 + 4^3 = 1 + 125 + 64 = 190+`

Write some code to determine whether a number is an Armstrong number.

== Source

=== Created by

* @wolf99

=== Contributed to by

* @computermouth
* @elyashiv
* @ryanplusplus

=== Based on

Wikipedia - https://en.wikipedia.org/wiki/Narcissistic_number

== Solution

Was told to consider using `snprintf` style/approach and to let the user take care of memory for the functions that count and decompose the number the array of digits.
That I should “take a pointer and a `size_t`”.
Also, “expose the maximum length needed for the array as a macro”.

