= How to Design Programs
:icons: font
:toc: right
:experilmental:

== The Book

The https://htdp.org/[How to Design Programs Book] (HtDP) is the book
that has most changed the way I think about, see and do programming.

I have previously gone through the link:++https://learning.edx.org/course/course-v1:UBCx+SPD1x+2T2016/home++[How to Code: Systematic Program Design Course on EDX] (part 1, 2 and 3, free,
later updated and renamed to How To Code) which is based on the HtDP book.
It is taught by no one less than linkhttps://en.wikipedia.org/wiki/Gregor_Kiczales:[Gregor Kiczales].

During the course — which also meant I perused the book a lot — I learned in practice what it means to use TDD to guide the design of programs (together with other concepts), and how tests serve as specification and documentation as much as they serve as tests proper.

This is the number one book I recommend to my friends (online or otherwise), coworkers, alien species, or other creatures whenever I am given a chance to speak about this book 😅.

By the way, the authors of the book sometimes answer questions on the https://groups.google.com/g/racket-users[racket-users] google group.

I'm slowly (as time permits) studying the book (not the course this time).
My previous solutions from the course exercises are in my link:https://gitlab.com/fernandobasso/htcspd[htcspd gitlab repository].

There is also the link:https://felleisen.org/matthias/htdp-plus.html[HtDP Plus] page with additional material that further extends the topics covered in the book.

== Design Recipes and Examples

* https://cs.berry.edu/webdocs-common/csc120/docs/recipes/htdd.html[CSC120 - How to Design Data Definitions (HtDD)].
* https://course.ccs.neu.edu/cs5010sp15/recipe.html[The Program Design Recipe].
* https://courses.edx.org/courses/course-v1:UBCx+SPD1x+2T2015/77860a93562d40bda45e452ea064998b/[Design Recipes | SPD1x | edX].

== Racket and BSL

* https://jeremykun.com/2011/10/02/a-taste-of-racket/[A Taste of Racket]
* http://docs.racket-lang.org/htdp/[Docs Racket Lang HTDP]
* http://www.crockford.com/javascript/little.html[The Little
JavaScripter] -- Douglas Crockford post.
* https://github.com/pkrumins/the-little-schemer
* https://docs.racket-lang.org/guide/intro.html[Racket guide on how to
run .rkt files].
* https://docs.racket-lang.org/guide/scripts.html[Racket docs on Racket
scripts].
* https://stackoverflow.com/questions/46045086/how-to-set-language-to-htdp-bsl-in-repl[How
to set language to htdp/bsl in REPL]
* https://gist.github.com/FernandoBasso/c3f772fff707af3cd2c592e60af77529[How
to use htpd/bsl from emacs or command line (my gist)]
* https://gitlab.com/jaor/geiser/-/issues/193[htdp/sbl support?] (issue
I openned for Geiser)
* https://stackoverflow.com/questions/25711372/emacs-key-bindings-in-drracket[Emacs
key bindings in DrRacket?]
* https://blog.racket-lang.org/2009/03/the-drscheme-repl-isnt-the-one-in-emacs.html[The
DrScheme repl isn’t the one in Emacs] -- Some rationale why DrScheme (now DrRacket) is not a REPL like in other Lisps.

1. Add the repos to `.emacs` or `init.el` as described in link:https://melpa.org/#/getting-started.

2. Run `M-x RET package-refresh-contents RET` (they don’t mention it in the tutorial).

3. Run `M-x RET package-install geiser RET`.

Geiser info pages:

.emacs
----
C-h i m Geiser RET
----

Read about installation notes for link:++http://www.nongnu.org/geiser/geiser_2.html#Installation++[Chicken Scheme stuff].

----
M-x run-geiser
----

Open a `.rkt` file in Emacs.
Whether you have Geiser repl running or not, hit kbd:[C-c C-a] and all functions and other definitions inside the
`.rkt` file will be available for use in the Geiser REPL.

In geiser REPL you can do:

.geiser/racket REPL
----
(enter! "foo.rkt")
(enter! "projs/main.rkt")
----

to load code on those files into the REPL.
It seems the files must start with *``#lang racket``* or something like that.
Or, if you are editing a `.rkt` file and want to “enter” it into the REPL:

----
C-c C-a
----

* http://www.nongnu.org/geiser/geiser_5.html
* https://docs.racket-lang.org/reference/interactive.html

== Teaching Languages — htdp/bsl 📖

.in a racket file
----
#lang htdp/bsl
----

* link:https://github.com/greghendershott/racket-mode/issues/125[Topic about images in htdp/bsl that shows some useful things].

To run tests like those with `check-expect`, your `.rkt` file must start with one of these (beginner/intermediate/advanced student languages.

The “+” means a few more features are available.

.list of available teaching languages
----
#lang htdp/bsl
#lang htdp/bsl+
#lang htdp/isl
#lang htdp/isl+
#lang htdp/asl
----

or

`#reader(lib "htdp-beginner-reader.ss" "lang")((modname area-tests) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))`

== Emacs, Geiser

kbd:[C-u C-c C-z] or kbd:[C-c C-a] brings one to the REPL in the current module/file.
It CAN DISPLAY IMAGES! 💖️

kbd:[C-c C-k] runs fine with the http languages (kbd:[C-c C-a] seems not work for the teaching languages).

Then, from `racket-mode`, do kbd:[C-c C-t] (runs `racket-test` and be happy.
From the command line,

----
$ raco test file.rkt
----

== Racket Mode

* https://racket-mode.com/

Docs for thing at point: kbd:[C-c C-d].

Insert lambda: kbd:[C-m-y].

== Other libs used in the book

* https://docs.racket-lang.org/teachpack/2htdpimage.html[2htdp/image] →
`bitmap`
* https://docs.racket-lang.org/teachpack/2htdpuniverse.html[2htdp/universe]
→ `animate`

== DrRacket

* https://docs.racket-lang.org/drracket/Keyboard_Shortcuts.html[DrRacket Keyboard Shortcuts] (Emacs!!! ⭐️)

kbd:[C-x o] to move from interactions to definition window.

[TIP]
====
To use `(bitmap "../images/foo.png")` make sure the file is saved so the relative path works, otherwise, with an unsaved buffer, DrRacket will try to load images relative to your home directory.
====

[WARNING]
====
If you paste/insert images through Racket’s UI, or your you set the language through the UI, you end up with unreadable source code files.
Use a header like one of these and see the next tip about “Determine language from source”.
====

[TIP]
====
To allow the line `#lang htdp/<some language>`, make sure “determine language from source” is selected in DrRacket’s bottom left corner.
====

[TIP]
====
On wide screens, you may find it useful to display the interactions pane on the right side (instead of at the bottom).
Go to “View → Use Horizontal Layout”.
There is a setting in Preferences too.
====

== Naming Source Files

Name each source file incrementally and append a descriptive name:

e001e-function.rkt (example from the book, note “e???e…”)
e002e-images.rkt e070p49-rocket-cond.rkt e071p50-tests-traffic-light.rkt

“n” is the exercise number, like “e070p49-rocket-cond.rkt”, meaing we
are at the file 70 written so far, but the practice exercise is 49.

For “World Programs”, use a “wp” as well, like in
“e075p51-wp-traffic-light.rkt”.

== Images

* https://www.pinterest.co.uk/sonjaeisenbeiss/drawing-animals-using-simple-shapes/[Drawing
Animals Using Simple Shapes]

== Other Links

* Racket Mode https://racket-mode.com/#Completion
* The Animated Guide to Paredit
http://danmidwood.com/content/2014/11/21/animated-paredit.html

== Other People’s Notes and Solutions

* link:++https://courses.edx.org/courses/course-v1:UBCx+SPD1x+2T2015/77860a93562d40bda45e452ea064998b/++[EDX Systematic Program Design Part 1 Summary]
* https://github.com/eareese/htdp-exercises/[eareese solutions] (gh) seems to have every single exercise solved
* https://github.com/adaliu-gh/htdp[adaliu-gh] (gh) seems to have the main exercises solved in code
* https://github.com/emaphis/HtDP2e-solutions[HtDP2e-solutions]
* https://github.com/adaliu-gh/htdp[adaliu-gh/htdp: COMPLETE! My solutions to exercises in htdp-2ed (most of them)]
* https://github.com/eareese/htdp-exercises/[eareese/htdp-exercises HTDP2e exercise solutions]

