= NPM
:toc: right
:icon: font
:stem: latexmath

== npm prefix

“Prefix” is an old term even from build systems in C programs where one would say `PREFIX=/usr/local/bin make install`.

In short, “prefix” in this kind of context simply means “the directory where something is to be installed, built, found, or treated as the current working directory.”

With `npm`, one can use `--prefix` to run a command in a project/package residing in some other directory.

=== Practical Example

From `/path/to/proj` (which contains its `package.json` file), we can run:

[source,shell-session]
----
$ cd /path/to/my/node/proj
$ npm --prefix ./my/sub/proj install
$ npm run --prefix ./my/sub/proj build
----

This will essentially run `npm install` and `npm run build` inside `./my/sub/proj`, and *not* in the current directory.
Of course, that directory must contain a valid `package.json` for those two `npm` commands to work.

As an analogy and further example, it is as if we are on a sub-shell, something like this:

[source,shell-session]
----
$ (cd ./my/sub/proj && npm install && npm run build)
----

After the above command finishes, the shell is back at the original directory, but inside the sub-shell, all the commands are run from  `./my/sub/proj` directory/context/prefix.

=== current prefix?

For local project the prefix will be the closest parent directory containing a `package.json`.
For global, it is the place where the active node version is installed (and where packages installed with `--global` will end up).

[source,shell-session]
----
$ npm --local prefix
/home/myuser/work/src/studies/devhowto/algds

$ npm --global prefix
/home/myuser/.nvm/versions/node/v16.17.0
----

=== References

* link:https://docs.npmjs.com/cli/v9/configuring-npm/folders[folders :: npm docs].
* link:https://docs.npmjs.com/cli/v9/commands/npm-prefix[npm-prefix :: npm docs].

== Random References and Resources

- link:https://nodejs.org/en/blog/npm/peer-dependencies/[Peer Dependencies :: Node.js blog].
- link:https://blog.npmjs.org/post/110924823920/npm-weekly-5[npm weekly blog (2015 post archive)].
- link:https://github.com/npm/npm/releases/tag/v3.0.0[npm 3 release notes]. Peer dependencies not longer installed by default.
- link:https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/[Presenting v7.0.0 of the npm CLI :: Github blog]. Peer dependencies installed by default again.
- link:https://stackoverflow.com/questions/35207380/how-to-install-npm-peer-dependencies-automatically[How to install peer dependencies automatically :: StackOverflow question].
- link:https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md[Install peer deps RFC/spec].
