= Intro
:pp: {plus}{plus}

My notes on the amazing https://youtu.be/wD5WGkOEJRs[Busy TypeScript Developer's Guide to Advanced TypeScript by Ted Neward (youtube)].

Some examples may have been adapted with newer TypeScript features, or made a little more realistic since I'm transcribing them from the talk slides to the webpages, which makes it more appropriate to have lengthier code with extra explanations or annotations.

== Some Interesting Comments From Ted Neward

TypeScript brings in new ideas (not just a copy of Java, C# or C{pp}):

____
TypeScript has so many interesting that are just not present in any other language that I've seen in the traditional static, object-oriented space.
____

TypeScript is not a trivial language (it is not Flow or React prop-types):

____
This is NOT a trivial language.

And please, don't think that TypeScript is just JavaScript with a little typing thrown in.

These guys are thinking a much, much longer more strategic game, and there is a lot more waiting in the wings.
We are not done here by any stretch of the imagination.
____

== Strict TypeScript Settings

This is not something recommended or mentioned in the video (that I recall), but which is a good idea to apply when studying or starting new projects.

Start your coding and studies with a setting like this in `tsconfig.json`:

----
{
  "compilerOptions": {
    /* Set the JavaScript language version for emitted JavaScript and include
     * compatible library declarations. */
    "target": "ES2017",

    /* Specify what module code is generated. */
    "module": "commonjs",

    /* Emit additional JavaScript to ease support for importing CommonJS
     * modules.  This enables `allowSyntheticDefaultImports` for type
     * compatibility. */
    "esModuleInterop": true,

    /* Ensure that casing is correct in imports. */
    "forceConsistentCasingInFileNames": true,

    /* Enable all strict type-checking options. */
    "strict": true,

    /* Skip type checking all .d.ts files. */
    "skipLibCheck": true,
  }
}
----

!!!
info

 This is [JSON5](https://json5.org/), a superset of JSON that, among other
 important things, allows the use of comments.

== Outline of Topics

In the video:

* https://youtu.be/wD5WGkOEJRs?t=34[00:34] Type Compatibility
 ** https://youtu.be/wD5WGkOEJRs?t=63[01:03] Structural Subtyping
 ** https://youtu.be/wD5WGkOEJRs?t=183[03:03] Type Assertions
 ** https://youtu.be/wD5WGkOEJRs?t=271[04:31] Type Guards
 ** https://youtu.be/wD5WGkOEJRs?t=300[05:00] typeof Type Guards
* https://youtu.be/wD5WGkOEJRs?t=368[06:08] Simple and Compound Types
 ** https://youtu.be/wD5WGkOEJRs?t=371[06:11] Arrays
 ** https://youtu.be/wD5WGkOEJRs?t=376[06:15] Arrays and Tuples
 ** https://youtu.be/wD5WGkOEJRs?t=389[06:29] Union Types
 ** https://youtu.be/wD5WGkOEJRs?t=415[06:55] Intersection Types
 ** https://youtu.be/wD5WGkOEJRs?t=562[09:22] Tuples
 ** https://youtu.be/wD5WGkOEJRs?t=570[10:28] Destructuring
 ** https://youtu.be/wD5WGkOEJRs?t=732[12:12] Enums
* https://youtu.be/wD5WGkOEJRs?t=773[12:53] Decorators
 ** https://youtu.be/wD5WGkOEJRs?t=966[16:16] Simple Example
 ** https://youtu.be/wD5WGkOEJRs?t=1171[19:39] Class Decorator Example
 ** https://youtu.be/wD5WGkOEJRs?t=1247[20:47] Method Decorator Example
 ** https://youtu.be/wD5WGkOEJRs?t=1249[22:56] Accessor Decorators
 ** https://youtu.be/wD5WGkOEJRs?t=1490[24:50] Property Decorators
 ** https://youtu.be/wD5WGkOEJRs?t=1490[25:45] Parameter Decorators
 ** https://youtu.be/wD5WGkOEJRs?t=1558[25:58] Order of Evaluation
 ** https://youtu.be/wD5WGkOEJRs?t=1623[27:03] Decorator Factories
 ** https://youtu.be/wD5WGkOEJRs?t=1632[27:12] Decorator Composition
* https://youtu.be/wD5WGkOEJRs?t=1758[29:18] Symbols
 ** https://youtu.be/wD5WGkOEJRs?t=1888[31:28] Usage
* https://youtu.be/wD5WGkOEJRs?t=1926[32:06] Iterators
 ** https://youtu.be/wD5WGkOEJRs?t=1930[32:10] Iterable Objects
 ** https://youtu.be/wD5WGkOEJRs?t=1981[32:58] Example Iterable/Iterator
* https://youtu.be/wD5WGkOEJRs?t=2083[34:43] Generators
* https://youtu.be/wD5WGkOEJRs?t=2451[40:51] Generics
 ** https://youtu.be/wD5WGkOEJRs?t=2987[49:47] Generic Interfaces
 ** https://youtu.be/wD5WGkOEJRs?t=2987[51:15] Generic Classes
 ** https://youtu.be/wD5WGkOEJRs?t=3137[52:17] Generic Constraints
 ** https://youtu.be/wD5WGkOEJRs?t=3249[54:09] Generic Parameter Defaults
* https://youtu.be/wD5WGkOEJRs?t=3411[56:49] Conditional Types

Ted also mentions this post:

https://www.freecodecamp.org/news/typescript-curry-ramda-types-f747e99744ab/

https://www.youtube.com/watch?v=wD5WGkOEJRs&lc=UgxhqwyNE3_jA1QOFtN4AaABAg[My comment on the video]
