= Hash Tables
:page-tags: algds, hash-table
:stem: latexmath
:icons: font
:toc: left

== hash function

[NOTE]
====
“Hash functions” for hashing hash tables/dictionary keys are not cryptographically secure hash functions.

The following hash function runs in constant time.
A cryptographically secure hash function does not run in constant time as the purpose and requirements are different.
====

A good hash (function) should be fast (stem:[O(1)]), distribute the keys uniformly and be deterministic (same key always produce the same result).

.very simple hash function
[source,javascript]
----
/**
 * A very bare-bones hash function that works for simple, lowercase,
 * ascii-only strings.
 */
function hash(str, len) {
  return [...str].reduce((acc, chr) => {
    var sub = chr.charCodeAt(0) - 96;
    return (acc * 31 + sub) % len;
  }, 0);
}
----

.node repl
----
> var strs = ['pink', 'blue', 'orange', 'email'];
> strs.map(s => hash(s, 10))
[ 0, 0, 0, 0 ]
----

[source,javascript]
----
/**
 * Prime numbers help to reduce the number of collisions.
 */
const OPTIMUS_PRIME = 31;

function hash(str, len) {
  return [...str].reduce((acc, chr) => {
    var sub = chr.charCodeAt(0) - 96;
    return (acc * OPTIMUS_PRIME + sub) % len;
  }, 0);
}
----

Note, though, what happens if we use a prime number as the length:

.node repl
----
> var strs = ['pink', 'blue', 'orange', 'email'];
> strs.map(s => hash(s, 10));
[ 0, 0, 0, 0 ]

> strs.map(s => hash(s, 11));
[ 1, 6, 1, 7 ]

> strs.map(s => hash(s, 13));
[ 5, 10, 10, 9 ]

> strs.map(s => hash(s, 31));
[ 11, 5, 5, 12 ]

> strs.map(s => hash(s, 51));
[ 26, 13, 21, 31 ]
----

Yes, using a prime number as the length helps to reduce collisions.
See “link:https://www.quora.com/Does-making-array-size-a-prime-number-help-in-hash-table-implementation-Why[Does making array size a prime number help in hash table implementation? Why? on Quora^]”.

== set(key, val)

* Accepts a key and a value.
* Stores the key/val pair in the hash table using the _Separate Chaining_ method of handling collisions.
* Always store using a nested structure because other values can potentially have to be stored in that same index.
* Return the index where the value was added.

== get(key)

* Accepts a key.
* Search for the key in the index for that key.
* Return `undefined` if the key is not found.

== keys()

Returns an array of all keys in the hash table.

Keys can never be duplicate in hash tables, so, nothing to worry about the returned keys.

== values()

Returns an array with all values in the hash table.

Values can have duplicates.
Multiple distinct keys can have the same values.
For example, multiple product SKUs can have the same price, or color, etc.
Multiple student IDs can have the same grade, etc...

Should we return duplicate values or only a single instance of each value?

== Time Complexity of Hash Tables

Average case:

* Insert: stem:[O(1)].
* Delete: stem:[O(1)].
* Access: stem:[O(1)].
* Search for a value: stem:[O(n)] as it would traverse potentially all the data.
