= Radix Sort
:page-tags: algorithm sort radix-sort
:toc: right
:stem: latexmath
:icons: font

== Intro to Radix Sort

Radix sort is a sorting algorithm that does not perform comparisons (“is this element greater or smaller than the other element?”).
Instead, it exploits the fact that information about the size of a number is encoded in the number of digits.

For example, a 5-digit number is greater than a 4-digit number, no matter what the digits themselves are.
11111 is certainly greater than 2222.
Note that the former has 5 digits; the later, 4.

Because it relies on properties of integers, it only works with integers.

We create 10 slots (or buckets) to account for the digits from 0 to 9 (in base 10).
Then, get the first digit (from right to left) and see in which bucket it would fall, and add the number to that bucket.

The numbers are not sorted in the buckets.
They are thrown there at the order they are found.

.radix sort in ascending order example
----
[57, 421, 752, 8510, 4176, 422, 9]
  ▪    ▪    ▪     ▪     ▪    ▪  ▪

Start with the ones place.

[0] → 8510
[1] → 421
[2] → 752, 422
[3]
[4]
[5]
[6]
[7] → 57
[8]
[9] → 9

Now, rewrite the list in the order the show up in the buckets.

[8510, 421, 752, 422, 57, 09]
   ▪    ▪    ▪    ▪   ▪   ▪

Loop again with the 10's place this time.
Numbers without a 10's place mean their 10's place
is zero and thus fall into the zero bucket.

[0] → 8510, 9
[1] → 421
[2] → 752, 422
[3]
[4]
[5]
[6]
[7] → 57
[8]
[9]

Again, rewrite the list in the order the show up in the buckets.

[8510, 009, 521, 752, 522, 057]
  ▪    ▪    ▪    ▪    ▪    ▪

Loop again with the 100's place this time.
Numbers without a 100's place mean their 100's place
is zero and thus fall into the zero bucket.

[0] → 8510, 9, 57
[1]
[2]
[3]
[4]
[5] → 521, 522
[6]
[7] → 752
[8]
[9]

Again, rewrite the list in the order the show up in the buckets.
Note how it starts to get in shape for an ascending order sort!

[8510, 0009, 0057, 0521, 0522, 0752]
 ▪     ▪     ▪     ▪     ▪     ▪

Loop again with the 1000's place this time.
Numbers without a 1000's place mean their 1000's place
is zero and thus fall into the zero bucket.

[0] → 9, 57, 521, 522, 752
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8] → 8510
[9]

Again rewrite the list in the order the show up in the buckets.

[9, 57, 521, 522, 752, 8510]

Sorted!

----

== Helper Functions

Writing Radix Sort is easier if we make use of a two helper functions:

* `takeDigit()`: Takes the nth digit (starting from the right).
* `mostDigits()`: Finds the number with most digits.

=== takeDigit() helper

[source,javascript,linenums]
----
import { abs, pow, countDigits } from './index.js';

/**
 * Take the first `len` digits from `num`.
 *
 * Negative numbers are treated as positive.
 *
 * If the number of digits in `num` is less than or equal to
 * `len`, simply return `num`.
 *
 * @example
 * takeDigits(1984, 4);
 * // → 1984
 *
 * takeDigits(-1984, 2);
 * // → 19
 *
 * @param {number} num
 * @param {number} len
 * @returns {number}
 */
function takeDigits(num, len) {
  if (typeof len !== "number" || len < 1)
    throw new RangeError("len must be a number >= 1");

  if (num === 0) return num;

  var n = abs(num);
  var numDigits = countDigits(n);

  if (numDigits <= len)
    return n | 0;

  return (n / pow(10, numDigits - len)) | 0;
}

export { takeDigits };
----

=== mostDigits() helper

[source,javascript,linenums]
----
import { countDigits, max } from '../jslib/index.js';

/**
 * Returns the length of digits on the largest number in `xs`.
 *
 * @sig [Int] -> Int
 */
function mostDigits(xs) {
  var maxDigits = 0;

  for (var i = 0; i < xs.length; ++i)
    maxDigits = max(countDigits(xs[i]), maxDigits);

  return maxDigits;
}

export { mostDigits };
----

== Radix Sort

Let's see an outline for sorting an array of integers in ascending order:

* Create a function that takes an array of integers.
* Get the length of digits of the largest number.
* Loop from `k = 0` up to that length.
** Create a bucket for each digit (empty array of 10 buckets (0 to 9) will do here, an array of 10 sub-arrays).
** Based on the number's stem:[k_{2}] digit, add it to its bucket.
** Replace the values in the original array with the values in the buckets, from 0 to 9.
   This is where we reorder them each time.
* Return the sorted array.

== Big O or Radix Sort

Complexity of Radix Sort is not universally agreed upon (check Wikipedia link below), but the following table gives some general idea.

[cols="^1,^1,^1,^1"]
|===
|T.C (best) |T.C (avg) |T.C (worst) | S.C

|stem:[O(nk)] | stem:[O(nk)] |stem:[O(nk)] |stem:[O(n + k)]
|===

`n` is the number of elements we are sorting and `k` is is the number of digits of the largest number.
If a number is really really big, and has a lot of digits, than the constant `k` is not to be ignored.

[WARNING]
====
Theoretically, radix sort can be faster than any of the comparison sorts (when working with integers), but in practice, because of the way integers and numbers in general are handled by computers, there are some counter arguments to consider (check Wikipedia article on Radix Sort).
====

latexmath:[C = \alpha + \beta Y^{\gamma} + \epsilon]

[stem]
++++
sqrt(4) = 2
++++

A matrix can be written as stem:[[[a,b\],[c,d\]\]((n),(k))].

== References and Resources

* link:https://en.wikipedia.org/wiki/Radix_sort[Radix Sort on Wikipedia^].
